name: supercluster
description: A port of MapBox's javascript supercluster library for fast marker clustering.
version: 1.0.0
homepage: https://github.com/rorystephenson/supercluster_dart.dart

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  kdbush: ^0.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
