name: supercluster
description: A port of MapBox's javascript supercluster library for fast clustering, with added mutable clustering support.
version: 2.3.0
homepage: https://github.com/rorystephenson/supercluster_dart

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  kdbush: ^0.0.5
  rbush: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  compute: ^1.0.2
  freezed: ^2.3.4
  lints: ^2.0.1
  test: ^1.24.3
  timing: ^1.0.1
