name: test_app
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  lat_lon_grid_plugin: ^0.2.7
  latlong2: ^0.9.0
  supercluster:
    path: ../../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
